### ISSUE TITLE
Latest Tag

### ISSUE THREAD

**Issue by marrts** [tesseract-robotics/tesseract#1003]
There hasn't been a tagged version in a while, despite some breaking changes across all the tesseract repos. I recall some talk about tagging a new version after all the forward declaration stuff was merged in, and I think that is done at this point.

- [x] https://github.com/tesseract-robotics/trajopt/pull/405
- [x] https://github.com/tesseract-robotics/tesseract/pull/1004
- [x] https://github.com/tesseract-robotics/tesseract/pull/1008

**Comment by Levi-Armstrong** [comment]
That is correct. I trying to get a few remaining improvements in this week and will create a new release this weekend. 

@marrts, @marip8 and @rjoomen, do you have anything you want to get merged before I cut a new release?

**Comment by rjoomen** [comment]
Maybe I have time to finish The tests for the SimplePlanner profiles, would be nice to have that included.

**Comment by rjoomen** [comment]
And this: tesseract-robotics/trajopt#405

**Comment by rjoomen** [comment]
And this: tesseract-robotics/tesseract#1004

**Comment by rjoomen** [comment]
And this: #1008

**Comment by Levi-Armstrong** [comment]
I believe everything has been merged.
