### ISSUE TITLE
Conda CI no longer working

### ISSUE THREAD

**Issue by Levi-Armstrong** [tesseract-robotics/tesseract#1023]
@johnwason How do I have conda install boost-stacktrace-backtrace?

**Comment by johnwason** [comment]
I think it is there but for some reason cmake is not finding it.

**Comment by Levi-Armstrong** [comment]
I do not see stacktrace_bactrace listed [here](https://github.com/conda-forge/boost-feedstock/blob/main/recipe/meta.yaml); should it be?

**Comment by johnwason** [comment]
Is this fixed now?
