### ISSUE TITLE
Parsing box with dimensions of 0

### ISSUE THREAD

**Issue by mpowelson** [tesseract-robotics/tesseract#343]
I'm not necessarily recommending we change this, but it looks like urdfdom is happy to parse a box with dimensions of 0. Tesseract does not. It returns a fairly generic `ErrorAttributeSizeConversion` error. 

Perhaps we could give a more specific error message to aid in tracking down what exactly is the problem with "legacy" urdfs.

**Comment by Levi-Armstrong** [comment]
Sure, just need to add a new error code and test.

**Comment by mpowelson** [comment]
I'm not sure when I will get to this, but it should be minimal. The code that needs to be changed is here
https://github.com/ros-industrial-consortium/tesseract/blob/master/tesseract/tesseract_urdf/include/tesseract_urdf/box.h

**Comment by Levi-Armstrong** [comment]
This has been addressed.
