### ISSUE TITLE
Efficient way to get joint names for manipulator

### ISSUE THREAD

**Issue by mpowelson** [tesseract-robotics/tesseract#539]
Often you need the names of a the joints associated with a manipulator but don't need the actual manipulator. Doing something like this `environment_monitor->getEnvironment()->getManipulatorManager()->getFwdKinematicSolver(manip)->getJointNames();` results in an unnecessary clone. I believe we used to have a getFwdKinematicsSolverConst (that presumably didn't clone it), but I think that was removed a while ago.

It seems that the same information is in the KinematicsInformation, but you'd have to know whether it was a chain, joint_group, etc. What is the recommended way to get the joint_names of a manipulator without cloning the manipulator?

**Comment by Levi-Armstrong** [comment]
A function has been added to the environment `getGroupJointNames()` which does what is requested.
