### ISSUE TITLE
Add copyLink() function to Environment

### ISSUE THREAD

**Issue by johnwason** [tesseract-robotics/tesseract#575]
Having a function that can be used to copy/clone a link would be useful for payload management. An example setup would be a scene with several payload types with fixed links outside of the workspace of the robot. The payloads can then be cloned into the workspace in the robot when they are being fed into the handling sequence. Once they have completed the sequence, they can be deleted. A potential signature for this function is:

    virtual bool copyLink(const tesseract_scene_graph::Link& link, const tesseract_scene_graph::Joint& joint, bool deep_copy = false, bool children = false);

If `deep_copy` is false, shapes, materials, etc would not be copied, and instead the existing data structures would be reused . If `children` is true, any child links would also be cloned. This would require a tree structure for the link and children. If false, only the specified link is copied.

**Comment by Levi-Armstrong** [comment]
This is capable using link clone method.
