### ISSUE TITLE
Expand JointLimits

### ISSUE THREAD

**Issue by mpowelson** [tesseract-robotics/tesseract#591]
Allow different upper/lower bounds on velocity and acceleration and add jerk limits. This will be useful if we write a wrapper for ruckig, which supports these things.

**Comment by Levi-Armstrong** [comment]
Sounds reasonable to me. Do you have a proposed updated to the data structure?

**Comment by mpowelson** [comment]
Not really. I was just posting this as a reminder of a potentially breaking change we might want to make soon. However, I would imagine something like this. We could use std::pair, but I kind of like position.lower better than position.first

```
class Bounds
{
   Bounds(double lower, double upper) ;
   Bounds(double upper) : upper(upper) { lower = -upper;}
   double lower;
   double upper;
}

class JointLimits
{
public:

  JointLimits() { this->clear(); }
  Bounds position;
  Bounds effort;
  Bounds velocity;
  Bounds acceleration;
  Bounds jerk;  
...
};

```

**Comment by Levi-Armstrong** [comment]
This is now supported
