### ISSUE TITLE
tesseract-robotics-superpack conda package gives "ImportError: liborocos-kdl.so.1.5: cannot open shared object file: No such file or directory"

### ISSUE THREAD

**Issue by clemense** [tesseract-robotics/tesseract#639]
Hi,
After installing `conda install -c tesseract-robotics tesseract-robotics-superpack` in a conda Python3.8 or Python3.9 environment, running any test program, e.g. `python test_simple_planner.py` gives:
```
ImportError: liborocos-kdl.so.1.5: cannot open shared object file: No such file or directory
```
This happens even though `conda list` returns:
```
orocos-kdl                1.5.1                he80948d_1    conda-forge
```

Any ideas how to fix this?
Thanks!

**Comment by johnwason** [comment]
You can fork the feedback to tinker with the builds. It will run the actions in your fork correctly, but won't upload so you'll need to pull the packages from the build artifacts.

**Comment by johnwason** [comment]
This should be fixed now

https://github.com/conda-forge/ompl-feedstock/pull/12
