### ISSUE TITLE
kinematics_plugin_config

### ISSUE THREAD

**Issue by mohamedsayed18** [tesseract-robotics/tesseract#651]
What are the correct values for the `kinematics_plugin_config`?
specifically what is the difference between these two classes `class: KDLInvKinChainLMAFactory` and `KDLInvKinChainNRFactory`?
In the base_link and tip_link, I add the same value for both classes which are specified in my chain
but my code fails at this assert 
https://github.com/ros-industrial/tesseract/blob/74492dc802c36e7310f937061622bc828b3f229b/tesseract_kinematics/core/src/kinematic_group.cpp#L108-L109

I'm having my chain defined as follows
```xml
    <group name="full_manipulator">
        <chain base_link="positioner_tool0" tip_link="tool0" />
        <!-- <chain base_link="world" tip_link="tool0" /> -->
    </group>
 ```

**Comment by mohamedsayed18** [comment]
I'm trying to execute two stateWaypoints(start and another point).
Somehow I'm still failing in this assert
https://github.com/tesseract-robotics/tesseract/blob/74492dc802c36e7310f937061622bc828b3f229b/tesseract_kinematics/core/src/kinematic_group.cpp#L108-L109

My working frames vector contains the positioner_tool0 as expected
but the `tip_link_pose.working_frame` is set to `world` regardless of the value in the ManipulatorInfo

**Comment by mohamedsayed18** [comment]
I think the error is in this line
https://github.com/tesseract-robotics/tesseract/blob/8445d507a2bbe3ec5b5e819a835a0d33758cc13b/tesseract_kinematics/core/include/tesseract_kinematics/core/validate.h#L64
Should it be the working_frame instead of the `getBaseLinkName`?

**Comment by Levi-Armstrong** [comment]
You are correct there is an issue with this function if you kinematic arrangement is rep. I have PR coming to fix the function.

**Comment by Levi-Armstrong** [comment]
I have opened PR #658 which should resolve the issue.
