### ISSUE TITLE
compile err/tesseract-0.9.5/tesseract_common/src/resource_locator.cpp:217:1:   required from here /usr/local/include/boost/serialization/shared_ptr_helper.hpp:182:20: error: no matching function for call to ‘std::map<const void*, std::shared_ptr<void>, std::less<const void*>, std::allocator<std::pair<const void* const, std::shared_ptr<void> > > >::insert(std::pair<const void*, std::shared_ptr<const tesseract_common::ResourceLocator> >)’              result = m_o_sp->insert(std::make_pair(oid, s));

### ISSUE THREAD

**Issue by dbdxnuliba** [tesseract-robotics/tesseract#762]
/tesseract-0.9.5/tesseract_common/src/resource_locator.cpp:217:1:   required from here
/usr/local/include/boost/serialization/shared_ptr_helper.hpp:182:20: error: no matching function for call to ‘std::map<const void*, std::shared_ptr<void>, std::less<const void*>, std::allocator<std::pair<const void* const, std::shared_ptr<void> > > >::insert(std::pair<const void*, std::shared_ptr<const tesseract_common::ResourceLocator> >)’
             result = m_o_sp->insert(std::make_pair(oid, s));
![image](https://user-images.githubusercontent.com/13350158/167428942-8c5ed423-402d-409c-b977-210a918d4a47.png)

**Comment by Levi-Armstrong** [comment]
Do you have the same issue if you use tag 0.9.6?

**Comment by Levi-Armstrong** [comment]
I believe this is an issue of having miss matched tags between tesseract, tesseract_planning and tesseract_ros.
