### ISSUE TITLE
how create BulletDiscreteBVHManager in python

### ISSUE THREAD

**Issue by lanmo0923** [tesseract-robotics/tesseract#830]
With reference to c++ case,i want create BulletDiscreteBVHManager in python,but i can not import  tesseract_collision_bullet. there are some difference in python and c++ api?
thank you

**Comment by Levi-Armstrong** [comment]
You might have better luck asking this on the tesseract_python repo. @johnwason has been maintaining the python wrappers there. There may be examples.

**Comment by johnwason** [comment]
@lanmo0923 did you figure out the problem? Typically the collision manager is created from the environment.

https://gist.github.com/johnwason/275eb1cd0655f9a92f523ce539b904bf

This example is a little out of date though, the resource loader is not going to work. @Levi-Armstrong are there some generic resource loaders in the core library now?

In this case, the SRDF file contains the links to the plugin file for collision checking. 

https://github.com/tesseract-robotics/tesseract/blob/015a9eb24b4f0eb2f3f6e4ae9f763976c49f4a8a/tesseract_support/urdf/lbr_iiwa_14_r820.srdf#L48

**Comment by Levi-Armstrong** [comment]
Yea, I just added one which extracts information from environment variables in version 0.14.0.

**Comment by Levi-Armstrong** [comment]
No response
