### ISSUE TITLE
ROS-Independent CI

### ISSUE THREAD

**Issue by marip8** [tesseract-robotics/tesseract#834]
Currently the Linux CI jobs use a custom docker image with ROS1 components installed. This is a bit unnecessary and causes problems for downstream ROS-independent or ROS2 builds that use the docker image generated by `tesseract` CI (like [here](https://github.com/tesseract-robotics/tesseract_ros2/pull/35#issuecomment-1353811194)). We should update the CI to be independent of ROS as in https://github.com/tesseract-robotics/boost_plugin_loader/pull/12.

**Comment by Levi-Armstrong** [comment]
What about using colcon but avoid using industrial_ci and ros dependendecies?

**Comment by marip8** [comment]
Yes, that's what I'm suggesting. That's what we did in the plugin loader library

**Comment by marip8** [comment]
I recently opened a PR to add this capability to `industrial_ci`: https://github.com/ros-industrial/industrial_ci/pull/818.

@Levi-Armstrong what do you think about transitioning the builds over to this branch of ICI? It would make the CI builds cleaner and make building downstream CI pipelines for `tesseract_ros/2` and other dependent projects easier to do.

**Comment by Levi-Armstrong** [comment]
I don't have an issue with that. Have you received any feedback on your PR?

**Comment by marip8** [comment]
Not yet and no comments on the corresponding issue I opened; I'm not sure who to ping for a review

**Comment by marip8** [comment]
Closing; addressed in #861
