### ISSUE TITLE
Update benchmark CI to push data to tesseract_doc

### ISSUE THREAD

**Issue by Levi-Armstrong** [tesseract-robotics/tesseract#855]
@marip8 It looks the action provides option to set the repository and data directory see below.

By default, this action assumes that `gh-pages` is your GitHub Pages branch and that `/dev/bench` is a path to put the benchmark dashboard page. If they don't fit your use case, please tweak them by `gh-pages-branch`, `gh-repository` and `benchmark-data-dir-path` inputs.

**Comment by marip8** [comment]
Closing; addressed in #856
