### ISSUE TITLE
FCL collision fails when a link has multiple collision objects

### ISSUE THREAD

**Issue by rjoomen** [tesseract-robotics/tesseract#894]
`fcl_utils.h` asserts that two collision objects have different names ([here](https://github.com/tesseract-robotics/tesseract/blob/master/tesseract_collision/fcl/src/fcl_utils.cpp#L211) and [here](https://github.com/tesseract-robotics/tesseract/blob/master/tesseract_collision/fcl/src/fcl_utils.cpp#L280)). If a link has multiple collision objects (for example after a convex decomposition), this assert fails.

I think the assert can be removed, as function [isContactAllowed()](https://github.com/tesseract-robotics/tesseract/blob/2a50d0f458f4f074ed465999521da51dc7159c30/tesseract_collision/core/src/common.cpp#L84) already disallows contact checks between objects with the same name.

Bullet does not have this issue.

**Comment by Levi-Armstrong** [comment]
I agree, they should be removed for fcl.
