### ISSUE TITLE
Update rosindustrial/tesseract:noetic docker image with Swig 4.1.1

### ISSUE THREAD

**Issue by johnwason** [tesseract-robotics/tesseract#898]
The updated tesseract_python wrappers require Swig version 4.1.1 to work properly. There have been some important improvements and bug fixes. Please update the docker image `rosindustrial/tesseract:noetic` to use the new Swig version.

**Comment by Levi-Armstrong** [comment]
I have kicked off the generation of the new images with the upgrade of swig. I will report back when they have been pushed to docker hub.

**Comment by Levi-Armstrong** [comment]
Noetic and Foxy have been update.
